import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Providers from "./Providers";

// Font files can be colocated inside of `app`
const myFont = localFont({
  src: [
    {
      path: "./fonts/IRANSansXV.woff2",
      weight: "100 900",
      style: "normal",
    },
    {
      path: "./fonts/IRANSansXV.woff",
      weight: "100 900",
      style: "normal",
    },
  ],
  display: "swap",
  variable: "--font-custom",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fa">
      <body className={myFont.className}>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
